USE quan_ly_ngan_hang;
GO

ALTER TABLE dbo.GiaoDich
DROP CONSTRAINT PK__GiaoDich__0A2A24EB8FB47A1C;
ALTER TABLE dbo.GiaoDich
ALTER COLUMN MaGiaoDich VARCHAR(36) NOT NULL;
ALTER TABLE dbo.GiaoDich
ADD CONSTRAINT PK_GiaoDich PRIMARY KEY (MaGiaoDich);
SELECT DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'GiaoDich'
  AND COLUMN_NAME = 'MaGiaoDich';
