USE quan_ly_ngan_hang;
GO
ALTER TABLE TaiKhoanTietKiem
DROP CONSTRAINT PK__TaiKhoan__20EDB1688E6D4696;
ALTER TABLE TaiKhoanTietKiem
ALTER COLUMN MaTietKiem VARCHAR(36) NOT NULL;
ALTER TABLE TaiKhoanTietKiem
ADD CONSTRAINT PK_TaiKhoanTietKiem
PRIMARY KEY (MaTietKiem);
